import { MenuTypes } from "../_types/types";

// Header, page.tsx에서 사용될 메뉴 데이터
export const menu: MenuTypes = {
    Windows: {
        name: "Windows 용어",
        icon: "/images/svg/windows.svg",
        src: "/images/svg/windows.svg",
        alt: "Windows",
        value: "windows",
        label: "Windows",
        width: 17,
        height: 17,
        priority: true,
    },
    Unix: {
        name: "Unix / Linux 용어",
        icon: "/images/svg/unix.svg",
        src: "/images/svg/unix.svg",
        alt: "Unix / Linux",
        value: "unix",
        label: "Unix / Linux",
        width: 17,
        height: 17,
        priority: true,
    },
    Network: {
        name: "Network 관련 신기술",
        icon: "/images/svg/network.svg",
        src: "/images/svg/network.svg",
        alt: "Network",
        value: "network",
        label: "Network",
        width: 17,
        height: 17,
        priority: true,
    },
    Software: {
        name: "Software 관련 신기술",
        icon: "/images/svg/software.svg",
        src: "/images/svg/software.svg",
        alt: "Software",
        value: "software",
        label: "Software",
        width: 17,
        height: 17,
        priority: true,
    },
    Hardware: {
        name: "Hardware 관련 신기술",
        icon: "/images/svg/hardware.svg",
        src: "/images/svg/hardware.svg",
        alt: "Hardware",
        value: "hardware",
        label: "Hardware",
        width: 17,
        height: 17,
        priority: true,
    }
}